# Generated by Django 3.2.7 on 2021-12-24 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingHistory',
            fields=[
                ('booking_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_Date', models.DateField()),
                ('trip_type', models.CharField(choices=[('Round trip', 'Round trip'), ('One way', 'One way'), ('Local', 'Local')], default='', max_length=50, null=True)),
                ('pickup_date_time', models.DateTimeField(blank=True, null=True)),
                ('drop_date', models.DateField(blank=True, null=True)),
                ('km_travelled', models.CharField(max_length=50)),
                ('pickup_point', models.CharField(max_length=150)),
                ('drop_point', models.CharField(max_length=150)),
                ('booked_by_user', models.CharField(max_length=20)),
                ('assigned_driver', models.CharField(max_length=20)),
                ('booked_vehicle', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='BrandModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelname', models.CharField(max_length=50)),
                ('brand_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=150)),
                ('model', models.CharField(max_length=150)),
                ('fare_per_km', models.PositiveIntegerField()),
                ('air_conditioned', models.BooleanField()),
                ('luggage_capacity', models.PositiveIntegerField()),
                ('number_of_seat', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.AutoField(primary_key=True, serialize=False)),
                ('driver_name', models.CharField(max_length=150)),
                ('mobile_no', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200, null=True)),
                ('km_driven', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(choices=[('UNDER VARIFICATION', 'UNDER VARIFICATION'), ('ACTIVE', 'ACTIVE'), ('OFFLINE', 'OFFLINE'), ('ON A RIDE', 'ON A RIDE')], default='UNDER VARIFICATION', max_length=50, null=True)),
                ('driveruser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerUser',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=150)),
                ('mobile_no', models.CharField(max_length=25)),
                ('wallet_amount', models.CharField(max_length=10, null=True)),
                ('email_id', models.EmailField(blank=True, max_length=60, null=True)),
                ('customeruser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookingDetails',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('trip_type', models.CharField(choices=[('Round trip', 'Round trip'), ('One way', 'One way'), ('Local', 'Local')], default='', max_length=50, null=True)),
                ('area', models.CharField(max_length=150)),
                ('Pickup_date_time', models.DateTimeField()),
                ('drop_point', models.CharField(max_length=150)),
                ('drop_date', models.DateField()),
                ('selected_car', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=25)),
                ('approx_km_travelling', models.CharField(max_length=50)),
                ('fare', models.CharField(max_length=50)),
                ('reject', models.BooleanField(default=False)),
                ('assign_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.driver')),
            ],
        ),
    ]
